export { default as AboutIntroSection } from './AboutIntroSection'
export { default as AboutHeroSection } from './AboutHeroSection'
export { default as AboutSkillsSection } from './AboutSkillsSection'
export { default as AboutBackgroundSection } from './AboutBackgroundSection'
export { default as AboutProjectsSection } from './AboutProjectsSection'
